name: Package Win32 SDK

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_BRANCH: 1.10.2

jobs:
  pkg-win32-sdk:
    runs-on: windows-2022

    steps:
      - name: Checkout Defold
        uses: actions/checkout@v4
        with:
          repository: defold/defold
          ref: ${{env.BUILD_BRANCH}}

      - name: Install Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.12

      - name: Package SDKS
        shell: bash
        run: ./scripts/package/package_win32_sdk.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: local_sdks
          path: local_sdks
          if-no-files-found: error

